CREATE TABLE IF NOT EXISTS agent_recipes (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    goal TEXT NOT NULL,
    steps JSONB NOT NULL,
    start_step_id TEXT NOT NULL,
    version INTEGER DEFAULT 1,
    status TEXT DEFAULT 'ACTIVE', -- 'DRAFT', 'ACTIVE', 'ARCHIVED'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
